/**
 * Auto-DDL synthesizer (Task #477)
 *
 * Reads every `pgTable` and `pgEnum` exported from `@shared/schema` and emits
 * idempotent CREATE/ALTER statements so the production database is always
 * brought up to match the schema source-of-truth on startup.
 *
 * Why this exists:
 * Twice now (#475, #476) prod went down because schema changes were applied
 * to dev via raw SQL but the matching `runStartupMigrations` block was never
 * added. This module makes that mirroring step automatic — adding a column
 * to `shared/schema.ts` is now the only step required for the change to
 * reach production on the next deploy.
 *
 * Scope (intentionally narrow & safe):
 *  - CREATE TYPE for enums (DO/EXCEPTION duplicate_object guard)
 *  - ALTER TYPE … ADD VALUE IF NOT EXISTS for additive enum evolution
 *  - CREATE TABLE IF NOT EXISTS with full column list, inline PK, inline UNIQUE
 *  - ALTER TABLE ADD COLUMN IF NOT EXISTS for every non-identity column
 *  - ALTER TABLE ADD CONSTRAINT (UNIQUE) guarded against duplicates
 *
 * Out of scope (handled by /migrations/*.sql files):
 *  - Type changes / column renames / drops (these need explicit migration SQL)
 *  - Foreign key constraint enforcement (we still let columns be created,
 *    referential integrity is added inline at table creation time only)
 *  - Indexes (use CREATE INDEX in a /migrations/*.sql file)
 *  - Check constraints
 *
 * Failure semantics: any synthesized statement that fails throws and aborts
 * startup. Every emitted statement is idempotent (`IF NOT EXISTS` / DO blocks
 * that swallow the duplicate-object error), so a failure here means real
 * drift (e.g. an existing column has a conflicting type) and must not be
 * silently shipped — that's the exact failure mode this task eliminates.
 */

import { is, SQL } from "drizzle-orm";
import {
  PgTable,
  PgDialect,
  getTableConfig,
  type PgColumn,
} from "drizzle-orm/pg-core";
import { isPgEnum } from "drizzle-orm/pg-core/columns/enum";
import type { Pool } from "pg";
import * as schema from "@shared/schema";

interface PgEnumLike {
  readonly enumName: string;
  readonly enumValues: readonly string[];
  readonly schema?: string;
}

const dialect = new PgDialect();

function quoteIdent(name: string): string {
  return `"${name.replace(/"/g, '""')}"`;
}

function quoteLiteral(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function isSqlExpression(value: unknown): value is SQL {
  if (value instanceof SQL) return true;
  return (
    typeof value === "object" &&
    value !== null &&
    "queryChunks" in value &&
    Array.isArray((value as { queryChunks: unknown }).queryChunks)
  );
}

function renderDefault(col: PgColumn): string | null {
  if (!col.hasDefault) return null;
  const def = col.default;
  if (def === undefined) {
    // Some defaults are runtime-only (defaultFn) — those can't be DDL'd.
    return null;
  }
  if (isSqlExpression(def)) {
    return dialect.sqlToQuery(def).sql;
  }
  if (typeof def === "string") return quoteLiteral(def);
  if (typeof def === "number") return String(def);
  if (typeof def === "boolean") return def ? "true" : "false";
  if (def === null) return "NULL";
  if (Array.isArray(def)) {
    const parts = def.map((v) =>
      typeof v === "string" ? quoteLiteral(v) : String(v),
    );
    return `ARRAY[${parts.join(", ")}]::${col.getSQLType()}`;
  }
  if (typeof def === "object") {
    return `${quoteLiteral(JSON.stringify(def))}::jsonb`;
  }
  return null;
}

function renderIdentityClause(col: PgColumn): string | null {
  const ident = col.generatedIdentity;
  if (!ident) return null;
  return ident.type === "always"
    ? "GENERATED ALWAYS AS IDENTITY"
    : "GENERATED BY DEFAULT AS IDENTITY";
}

function isIdentityColumn(col: PgColumn): boolean {
  return col.generatedIdentity !== undefined;
}

function renderColumnDefinition(col: PgColumn): string {
  const parts: string[] = [quoteIdent(col.name), col.getSQLType()];
  const identity = renderIdentityClause(col);
  if (identity) {
    parts.push(identity);
  } else {
    const def = renderDefault(col);
    if (def !== null) parts.push(`DEFAULT ${def}`);
  }
  if (col.notNull) parts.push("NOT NULL");
  if (col.primary) parts.push("PRIMARY KEY");
  if (col.isUnique) parts.push("UNIQUE");
  return parts.join(" ");
}

interface PendingStatement {
  sql: string;
  description: string;
  /**
   * If true, a failure aborts startup. All synthesized statements are
   * idempotent, so any failure means real drift the operator must address.
   */
  required: boolean;
}

function collectStatements(): PendingStatement[] {
  const stmts: PendingStatement[] = [];
  const exports = Object.values(schema as Record<string, unknown>);

  // 1. Enums: create the type, then ensure every declared value is present
  //    (additive enum evolution — adding a value to a pgEnum reaches prod).
  for (const exp of exports) {
    if (!isPgEnum(exp)) continue;
    const e = exp as unknown as PgEnumLike;
    const typeId = e.schema
      ? `${quoteIdent(e.schema)}.${quoteIdent(e.enumName)}`
      : quoteIdent(e.enumName);
    const values = e.enumValues.map(quoteLiteral).join(", ");
    stmts.push({
      description: `enum ${e.enumName}`,
      required: true,
      sql: `DO $$ BEGIN
        CREATE TYPE ${typeId} AS ENUM (${values});
      EXCEPTION WHEN duplicate_object THEN NULL; END $$;`,
    });
    for (const value of e.enumValues) {
      stmts.push({
        description: `enum ${e.enumName} value ${value}`,
        required: true,
        // ADD VALUE IF NOT EXISTS is supported in PG12+. It can't run inside
        // a transaction block, but pool.query single-statements run with
        // implicit autocommit so this is fine.
        sql: `ALTER TYPE ${typeId} ADD VALUE IF NOT EXISTS ${quoteLiteral(value)};`,
      });
    }
  }

  // 2. Tables: CREATE TABLE IF NOT EXISTS with everything inline.
  for (const exp of exports) {
    if (!is(exp, PgTable)) continue;
    const cfg = getTableConfig(exp);
    const tableName = cfg.name;
    const tableId = cfg.schema
      ? `${quoteIdent(cfg.schema)}.${quoteIdent(tableName)}`
      : quoteIdent(tableName);

    const inlinePk = cfg.columns.some((c) => c.primary);
    const compositePk =
      !inlinePk && cfg.primaryKeys.length > 0 ? cfg.primaryKeys[0] : null;

    const columnDefs = cfg.columns.map(renderColumnDefinition);
    if (compositePk) {
      const pkCols = compositePk.columns
        .map((c) => quoteIdent(c.name))
        .join(", ");
      columnDefs.push(`PRIMARY KEY (${pkCols})`);
    }
    for (const u of cfg.uniqueConstraints) {
      const uCols = u.columns.map((c) => quoteIdent(c.name)).join(", ");
      const name = u.name ? `CONSTRAINT ${quoteIdent(u.name)} ` : "";
      columnDefs.push(`${name}UNIQUE (${uCols})`);
    }

    stmts.push({
      description: `create table ${tableName}`,
      required: true,
      sql: `CREATE TABLE IF NOT EXISTS ${tableId} (\n  ${columnDefs.join(",\n  ")}\n);`,
    });
  }

  // 3. ALTER TABLE ADD COLUMN IF NOT EXISTS for every non-identity column.
  //    This is what catches "schema changed but table already exists in prod".
  for (const exp of exports) {
    if (!is(exp, PgTable)) continue;
    const cfg = getTableConfig(exp);
    const tableId = cfg.schema
      ? `${quoteIdent(cfg.schema)}.${quoteIdent(cfg.name)}`
      : quoteIdent(cfg.name);

    for (const col of cfg.columns) {
      if (isIdentityColumn(col)) continue;
      if (col.primary) continue; // PK columns belong to CREATE TABLE only.
      const parts: string[] = [quoteIdent(col.name), col.getSQLType()];
      const def = renderDefault(col);
      if (def !== null) parts.push(`DEFAULT ${def}`);
      // NOT NULL is risky on ADD COLUMN if the table already has rows and no
      // default — Postgres will reject it. Only enforce NOT NULL when there's
      // a default to backfill with.
      if (col.notNull && def !== null) parts.push("NOT NULL");
      stmts.push({
        description: `add column ${cfg.name}.${col.name}`,
        required: true,
        sql: `ALTER TABLE ${tableId} ADD COLUMN IF NOT EXISTS ${parts.join(" ")};`,
      });
    }

    for (const u of cfg.uniqueConstraints) {
      const uCols = u.columns.map((c) => quoteIdent(c.name)).join(", ");
      const name =
        u.name ?? `${cfg.name}_${u.columns.map((c) => c.name).join("_")}_unique`;
      stmts.push({
        description: `unique constraint ${name}`,
        // Not required: a column-data conflict could legitimately block the
        // constraint and that's a separate fix; tables and columns are what
        // matters for "prod doesn't 500 on missing schema".
        required: false,
        sql: `DO $$ BEGIN
          ALTER TABLE ${tableId} ADD CONSTRAINT ${quoteIdent(name)} UNIQUE (${uCols});
        EXCEPTION WHEN duplicate_object THEN NULL; WHEN duplicate_table THEN NULL; END $$;`,
      });
    }
  }

  return stmts;
}

function describeError(err: unknown): string {
  if (err instanceof Error) return err.message;
  if (typeof err === "string") return err;
  return JSON.stringify(err);
}

export async function applySchemaFromCode(pool: Pool): Promise<void> {
  const stmts = collectStatements();
  let applied = 0;
  let skipped = 0;
  for (const stmt of stmts) {
    try {
      await pool.query(stmt.sql);
      applied++;
    } catch (err: unknown) {
      const msg = describeError(err);
      if (stmt.required) {
        // Fail loud and fast — this is real drift the operator must fix.
        // Silently continuing here is the failure mode that put #475/#476
        // into production in the first place.
        throw new Error(
          `[schema-sync] required statement failed (${stmt.description}): ${msg}\nSQL: ${stmt.sql}`,
        );
      }
      skipped++;
      console.warn(`[schema-sync] skipped (${stmt.description}): ${msg}`);
    }
  }
  console.log(
    `[schema-sync] applied ${applied} statement(s), skipped ${skipped} non-required (${stmts.length} total)`,
  );
}
