// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/AsymmetricTwoPane.tsx": () => import("../components/mockups/landing-variants/AsymmetricTwoPane.tsx"),
  "./components/mockups/landing-variants/EditorialBroadsheet.tsx": () => import("../components/mockups/landing-variants/EditorialBroadsheet.tsx"),
  "./components/mockups/landing-variants/ProductLauncher.tsx": () => import("../components/mockups/landing-variants/ProductLauncher.tsx")
};
