import { useState } from "react";
import { X, Sparkles, Loader2, BookOpen, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import { useGrokBriefing, type NewsAiSettings } from "@/hooks/use-news-ai";

interface DailyBriefingProps {
  aiSettings: NewsAiSettings;
}

function BriefingModal({ onClose, data, isLoading }: {
  onClose: () => void;
  data: { greeting: string; sections: Array<{ category: string; summary: string; highlights: string[] }>; closingThought: string } | null;
  isLoading: boolean;
}) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" data-testid="daily-briefing-modal">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-background border rounded-2xl shadow-2xl w-full max-w-2xl max-h-[85vh] overflow-y-auto">
        <div className="sticky top-0 bg-background/95 backdrop-blur-sm border-b z-10 flex items-center justify-between p-4">
          <div className="flex items-center gap-2">
            <BookOpen className="h-4 w-4 text-primary" />
            <span className="text-sm font-bold">AI Daily Briefing</span>
            <Badge variant="secondary" className="text-[10px]">
              <Sparkles className="h-2.5 w-2.5 mr-0.5" />Grok
            </Badge>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="h-8 w-8" data-testid="button-close-briefing">
            <X className="h-4 w-4" />
          </Button>
        </div>

        <div className="p-6 space-y-6">
          {isLoading ? (
            <div className="space-y-4">
              <Skeleton className="h-6 w-3/4" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-5/6" />
              <Skeleton className="h-32 w-full rounded-xl" />
              <Skeleton className="h-32 w-full rounded-xl" />
              <Skeleton className="h-4 w-2/3" />
            </div>
          ) : data ? (
            <>
              <div className="text-center pb-4 border-b">
                <p className="text-lg font-serif font-bold text-foreground">{data.greeting}</p>
                <p className="text-xs text-muted-foreground mt-1">
                  {new Date().toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" })}
                </p>
              </div>

              {data.sections.map((section, i) => (
                <div key={i} className="border rounded-xl p-4 bg-muted/20" data-testid={`briefing-section-${i}`}>
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant="outline" className="text-xs font-semibold">{section.category}</Badge>
                  </div>
                  <p className="text-sm text-foreground leading-relaxed mb-3">{section.summary}</p>
                  {section.highlights.length > 0 && (
                    <ul className="space-y-1.5">
                      {section.highlights.map((h, j) => (
                        <li key={j} className="flex items-start gap-2 text-xs text-muted-foreground">
                          <ChevronRight className="h-3 w-3 text-primary mt-0.5 shrink-0" />
                          <span>{h}</span>
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              ))}

              {data.closingThought && (
                <div className="text-center pt-4 border-t">
                  <p className="text-sm text-muted-foreground italic">"{data.closingThought}"</p>
                  <div className="flex items-center justify-center gap-1 mt-2 text-[10px] text-primary/60">
                    <Sparkles className="h-2.5 w-2.5" />
                    <span>Generated by Grok AI</span>
                  </div>
                </div>
              )}
            </>
          ) : (
            <p className="text-sm text-muted-foreground text-center py-8">Failed to generate briefing. Please try again.</p>
          )}
        </div>
      </div>
    </div>
  );
}

export function DailyBriefingFab({ aiSettings }: DailyBriefingProps) {
  const [open, setOpen] = useState(false);
  const briefingMutation = useGrokBriefing();

  if (!aiSettings.aiAvailable || !aiSettings.briefingEnabled) return null;

  const handleOpen = () => {
    setOpen(true);
    if (!briefingMutation.data && !briefingMutation.isPending) {
      briefingMutation.mutate();
    }
  };

  return (
    <>
      <button
        onClick={handleOpen}
        className="fixed bottom-6 right-6 z-40 flex items-center gap-2 bg-primary text-primary-foreground px-4 py-2.5 rounded-full shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-200 group"
        data-testid="daily-briefing-fab"
      >
        <Sparkles className="h-4 w-4 group-hover:motion-safe:animate-pulse" />
        <span className="text-sm font-semibold hidden sm:inline">AI Daily Briefing</span>
        <span className="text-sm font-semibold sm:hidden">Briefing</span>
      </button>

      {open && (
        <BriefingModal
          onClose={() => setOpen(false)}
          data={briefingMutation.data ?? null}
          isLoading={briefingMutation.isPending}
        />
      )}
    </>
  );
}
